### PR TITLE
Fix Hurd build

### PR DESCRIPTION
**Pull request by sthibaul**

### CODE REVIEW

**Comment by sthibaul** [comment]
ping?

**Comment by ottok** [comment]
Related to Debian bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=906305
Ping @temeo @ayurchen

**Comment by ottok** [comment]
Related to Debian bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=906305
Ping @temeo @ayurchen

**Comment by ottok** [comment]
Please merge this. It has been applied on Debian official releases of Galera 3 for some while already and they are working fine.

**Comment by ottok** [comment]
@temeo Please merge this. It has been applied on Debian official releases of Galera 3 for some while already and they are working fine.

**Comment by temeo** [comment]
Was merged in commit 54643f518b5bcb4911a1abf5d352a2c01c1c2087.

**Pull request closed without merging**
