### PR TITLE
Meaningful err messages

### PR DESCRIPTION
**Pull request by grooverdan**

### CODE REVIEW

**Comment by grooverdan** [comment]
worth considering yet?

**Comment by grooverdan** [comment]
Using system error messages for application code problem just obscures the real cause of what's wrong. Please don't do it. Its not that hard to write a text description of the reason for a failure. Looking forward to a code acceptance policy any year now.

https://github.com/codership/galera/blob/3.x/gcomm/src/pc.cpp#L162

**Comment by ayurchen** [comment]
>  Its not that hard to write a text description of the reason for a failure.

it is, Daniel. For example most descriptions you offered in this patch either do not make any sense or are confusing (to me) - this is the reason it has not been merged right away back then. Somebody needs to take time and fix them. And I bet you won't like the result ;)

**Comment by grooverdan** [comment]
Good to get some constructive feedback.

Can you indicate which messages you are happy with so I can look at the others?

Using system messages just leads people down the wrong track as they are tied to tcp/ip conditions that actually haven't happened.

**Comment by ghost** [comment]
I also wasted a day before I found out that galera tried to match my donor name to the node hostname, which were not the same(because I use ips for gcomm), so I ended up with "no route to host" found, which is rather low level and hence I spend hours trying to chase imaginary network issues.

**Comment by grooverdan** [comment]
:snail:

**Comment by ylacancellera** [comment]
For what it's worth, I believe this is still lacking and should be implemented one way or another.
This would be valuable to make Galera more accessible, as this kind of confusion mainly impacts newcomers (rightfully).

**Comment by hartmut-mariadb** [comment]
"Using system error messages for application code problem just obscures the real cause of what's wrong."

I couldn't agree more. I have bitten by this multiple times now, error logs showing system error strings hinting towards problems on the kernel or libc level, while the actual cause was an error raised by Galera itself, but re-using, no, lets say ab-using, a well esteblished system error code for its own purpose

**Comment by williamdes** [comment]
@temeo could this 2014 PR be considered into closed or merged ?
This error message is still problematic for users.
Ref https://jira.mariadb.org/browse/MDEV-23988

**Comment by grooverdan** [comment]
Closed via - https://github.com/codership/galera/commit/f12ff7e6ff7899c2261ce8c1df864dcec1855d33

Thanks @temeo

**Comment by ylacancellera** [comment]
So was it merged ? 
(Or at least was it taken into account?

Because I still argue it would help making galera easier to newcomers

**Comment by grooverdan** [comment]
Per commit link - an alternate implementation was done that achieves the same outcome.

**Pull request closed without merging**
