### PR TITLE
Fix kfreebsd build

### PR DESCRIPTION
**Pull request by sthibaul**

### CODE REVIEW

**Comment by sthibaul** [comment]
ping?

**Comment by ottok** [comment]
Ping @temeo @ayurchen 

I think this would have fixes some bugs detected in Debian if merged. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=906081

**Comment by ottok** [comment]
Ping @temeo @ayurchen

I think this would have fixes some bugs detected in Debian if merged. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=906081

**Comment by ottok** [comment]
Please merge this. It has been applied on Debian official releases of Galera 3 for some while already and they are working fine.

**Comment by ottok** [comment]
@temeo Please merge this. It has been applied on Debian official releases of Galera 3 for some while already and they are working fine.

**Comment by temeo** [comment]
Was merged in commit eaccfb29ddbd706852a2e5d3a5c1f9f2c94f65f7.

**Pull request closed without merging**
