### PR TITLE
Travis - container build

### PR DESCRIPTION
**Pull request by grooverdan**
@philip-galera , nice work on getting a travis build going.

Here is a container version. Their containers seem to be less loaded - http://www.traviscistatus.com/

Needs travis folks to whitelist check: https://github.com/travis-ci/travis-ci/issues/3816

Alternatives in containers are on the way if you intend to build with other more recent compilers: https://github.com/travis-ci/travis-ci/issues/3668

also consider coveralls.io and https://scan.coverity.com/travis_ci for getting a bit more information out of your travis builds.

### CODE REVIEW

**Comment by ayurchen** [comment]
well, I guess it is pending https://github.com/travis-ci/travis-ci/issues/3816 ;)

**Comment by grooverdan** [comment]
"All is well"

oddly gcc-4.6.3 (default) https://travis-ci.org/openquery/galera/jobs/64653151 and gcc-4.9 https://travis-ci.org/openquery/galera/jobs/64653151 generated internal compile errors however 5.1 worked with one code change  94b139b.

Uses travis-ci ccache so builds should stay quick

**Comment by ayurchen** [comment]
Hi, Daniel.
Internal compiler errors are most likely due to lack of RAM (i.e. too many processes running in parallel) - that was a reason for a such elaborate MAX_JOBS calculation.

**Comment by ayurchen** [comment]
Dan, there are more issues. For example http://lint.travis-ci.org/ complains:
    - in cache section: unexpected key ccache, dropping
    - value for addons section is empty, dropping
    - in addons section: unexpected key apt, dropping

What shall we make out it?

**Comment by ayurchen** [comment]
Merged into travis branch

**Comment by grooverdan** [comment]
the lint errors - they are errors in the lint program - couldn't find the exact upstream issue however https://github.com/travis-ci/travis-yaml/issues/30 indicates they aren't good at keeping it up to date.

thanks for identifying ICE as memory limitations - was having the same trouble with mariadb.

Thanks for finding this useful.

**Comment by philip-galera** [comment]
Merged into master.

**Pull request closed without merging**
