### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by eworm-de**

### CODE REVIEW

**Comment by ayurchen** [comment]
Philip, I don't have a problem with this patch as long as it builds on all systems we need it to build.

**Comment by philip-galera** [comment]
@eworm-de  Thank you for your contribution. Will you be willing to accept our Contributor License Agreement so that we can merge the contribution? If yes, let me know and I will provide the details.

**Comment by eworm-de** [comment]
Sure. I am following the steps at https://www.clahub.com/agreements/codership/galera, but it returns:

> We're sorry, but something went wrong.

**Comment by philip-galera** [comment]
@eworm-de: Yes, this service seems to be unreliable at times. Can you please add your name to the CONTRIBUTORS.txt file , and then use `commit -s` to commit the changes to this file. Push the new commit so that it becomes part of the pull request. Thank you!

**Comment by eworm-de** [comment]
Done.
Do you want the other commits with a sign-off-line as well?

**Comment by philip-galera** [comment]
I think we are good with respect to the CLA. Your change compiles on all supported platforms so I am now merging it. Thank you.

**Pull request merged**
