### PR TITLE
Travis: test clang-3.8

### PR DESCRIPTION
**Pull request by grooverdan**
for when #412 is fixed

### CODE REVIEW

**Comment by ayurchen** [comment]
Dan, I'm not sure hardcoding compiler version is a good idea.

**Comment by grooverdan** [comment]
Its just picking a latest travis CI available repo version and package for testing - https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json#L188. A version had to be selected.

Using more recent compilers for testing bleeding edge development helps distos that pick it up with recent compilers to be able to work.

**Comment by ari** [comment]
Can this now be merged?

**Comment by grooverdan** [comment]
travis has moved on https://travis-ci.org/github/codership/galera

**Pull request closed without merging**
