### PR TITLE
Fixes codership/galera#186 - all sorts of problems with garbd system scr...

### PR DESCRIPTION
**Pull request by ayurchen**
...ipts
- removes pre-3.x nc/nmap probing for live nodes in garbd system scripts
- encloses garbd parameters in single quotes and makes sure they are passed properly to the daemon start function
- removes final exit 0 in garb.sh that masked real error code
- makes sure to return error if there is no process or PID file can't be created
- removes stale PID file if found on startup instead of freaking out and forcing the user to do it manually
- removes dependency on nc/nmap from RPM spec

Note that service garb start will return 0 before garbd successfuly joins the
cluster. This is due to both potentially long wait times and forking into
daemon before the actual library initialization due to its multithreaded
character. However cluster connection errors will be logged to syslog/logfile.

Any firther improvements in error code reporting will require garbd code
refactoring.

### CODE REVIEW

**Comment by ayurchen** [comment]
Philip, would it be safe to assign you for review of this pull request (packaging/system startup) ?

**Comment by philip-galera** [comment]
The same bash block that you are changing is also used in debian/galera-arbitrator-3.garb.init . Can you fix it there as well?

**Comment by ayurchen** [comment]
To me debian/galera-arbitrator-3.garb.init looks like

```
$ ls -l galera-arbitrator-3.garb.init 
lrwxrwxrwx 1 ayurchen ayurchen 21 Jan 29 12:19 galera-arbitrator-3.garb.init -> ../garb/files/garb.sh
```

isn't it the same for you?

**Comment by philip-galera** [comment]
Yes, you are right. Let me run a complete package build and test and I will merge.

**Comment by philip-galera** [comment]
With the new changes apt-get install fails because it attempts to start the garbd service which in turn fails because the default config file is not good enough. So before this is merged we need a fix from Otto that will make the service not start on package installation.

**Comment by temeo** [comment]
If netcat dependency has been removed, dependency should be removed also from debian packaging. See package galera-arbitrator-3.x definition in debian/control.

**Comment by ayurchen** [comment]
This also fixes codership/galera#262

**Comment by philip-galera** [comment]
I messed up this branch, will open a new one and will merge if the build succeeds.

**Pull request closed without merging**
