### PR TITLE
Display an error on missing SSL parameters

### PR DESCRIPTION
**Pull request by gjedeer**
Currently when missing an SSL parameter, the behavior is to print:

```
Exception in creating receive loop.
```

which is not very helpful.

More: issue #399

### CODE REVIEW

**Comment by ayurchen** [comment]
Philip, the pull request looks generally good, but I won't just close the ticket as it is reasonable to expect socket.ssl_cipher to have a default value.

**Comment by philip-galera** [comment]
@gjedeer . Thank you for your contribution and apologies for the slow response. Will you be willing to accept our Contributor License Agreement so that we can merge the contribution? If yes, let me know and I will provide the details.

**Comment by gjedeer** [comment]
@philip-galera no problem, I can accept it

**Comment by philip-galera** [comment]
@gjedeer: Can you please do the following two quick things:
1. Sign the CLA by visiting

https://www.clahub.com/agreements/codership/galera

(this service sometimes does not work, let us know if you get an error)
1. Add your name to the CONTRIBUTORS.txt file , and then use `commit -s` to commit the changes to this file. Push the new commit so that it becomes part of the pull request.

Thank you.

**Comment by gjedeer** [comment]
"We're sorry, but something went wrong." is what I'm getting from
clahub.com

**Comment by philip-galera** [comment]
@gjedeer I see. Can you then do the second way of accepting the CLA? Add your name to the CONTRIBUTORS.txt file , and then use commit -s to commit the changes to this file. Push the new commit so that it becomes part of the pull request.

**Comment by gjedeer** [comment]
Okay, done

**Comment by philip-galera** [comment]
@gjedeer Thank you, merged

**Pull request merged**
